# Generated by Django 6.0.1 on 2026-01-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesubmission',
            name='case_title',
            field=models.CharField(default='Untitled Case', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casesubmission',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='case_docs/'),
        ),
        migrations.AddField(
            model_name='casesubmission',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casesubmission',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
