# Generated by Django 6.0.1 on 2026-02-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_casesubmission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesubmission',
            name='is_flagged',
        ),
        migrations.AddField(
            model_name='casesubmission',
            name='analysis_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casesubmission',
            name='case_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
